# Generated by Django 3.0 on 2020-04-15 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentcontactapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdata',
            name='scontact',
            field=models.IntegerField(),
        ),
    ]
