# Generated by Django 3.0 on 2020-04-15 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentcontactapp', '0003_studentdata_gender'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentdata',
            old_name='gender',
            new_name='sgender',
        ),
    ]
